Repository ornikar/shared-configs, pull requests merged in 2019-09, with the labels that each got.

#267 chore: execute typescript css linter if typescript exists in project
  @ornikar/repo-config-react/createLintStagedConfig.js
Labels: :ok_hand: code/approved

#264 fix: run yarn-update-lock on package.json changes [no issue]
  @ornikar/repo-config/createLintStagedConfig.js
Labels: :ok_hand: code/approved

#268 feat(renovate-config): group ornikar components [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#270 fix: parse JSON file instead of stringifying it [no issue]
  @ornikar/repo-config-react/createLintStagedConfig.js
Labels: :ok_hand: code/approved, frontend

#254 fix: use same localIdentName [no issue]
  @ornikar/rollup-config/createRollupConfig.js
  @ornikar/storybook-config/webpack-configs/lib.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#260 fix(renovate-config): only patch should be merged automaticly for @types [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#269 fix: svg transform [no issue]
  @ornikar/jest-config-react/fileTransform.js
  @ornikar/jest-config-react/jest-preset.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend
