Repository ornikar/shared-configs, pull requests merged in 2019-05, with the labels that each got.

#170 fix: shallow snapshots with decorators [no issue]
  @ornikar/jest-config-react/__mocks__/@storybook/react.js
Labels: :ok_hand: code/approved, :soon: automerge

#172 feat: enable import/no-anonymous-default-export for functions [no issue]
  @ornikar/eslint-config-babel-use/index.js
Labels: :ok_hand: code/approved

#181 chore: update eslint-plugin-import to fix typescript issue [no issue]
  @ornikar/eslint-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved

#182 chore: renovate-config ONK-3277
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge

#184 feat: renovate labels config [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge

#186 feat: renovate add missing label automerge [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/needs-review

#183 feat: add reviewflow infos in renovate prs [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge

#188 feat: prettier config [no issue]
  @ornikar/browserslist-config/degraded-support.js
  @ornikar/browserslist-config/full-support.js
  @ornikar/eslint-config-typescript/index.js
  @ornikar/eslint-config/rules/best-practices.js
  @ornikar/eslint-config/rules/style.js
  @ornikar/jest-config-react/__mocks__/@storybook/addon-knobs.js
  @ornikar/jest-config-react/__mocks__/@storybook/react.js
  @ornikar/jest-config-react/__mocks__/storybook-react-router.js
  @ornikar/jest-config-react/jest-preset.js
  @ornikar/jest-config/test-setup-after-env.js
  @ornikar/jest-config/test-shim.js
  @ornikar/postcss-config/index.js
  @ornikar/prettier-config/index.js
  @ornikar/prettier-config/package.json
  @ornikar/stylelint-config/index.js
  package.json
Labels: :ok_hand: code/approved
