Repository ornikar/shared-configs, pull requests merged in 2020-01, with the labels that each got.

#302 feat: add lerna config [no issue]
  .circleci/config.yml
  @ornikar/lerna-config/generate-tsconfig-files.js
  @ornikar/lerna-config/package.json
  @ornikar/repo-config/createLintStagedConfig.js
Labels: :ok_hand: code/approved, frontend

#316 feat: intl shared configs CORE-571
  .circleci/config.yml
  @ornikar/eslint-config-formatjs/README.md
  @ornikar/eslint-config-formatjs/index.js
  @ornikar/eslint-config-formatjs/package.json
  @ornikar/eslint-config-formatjs/plugins/formatjs.js
  @ornikar/intl-config/generate-translations.js
  @ornikar/intl-config/package.json
  README.md
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#318 feat: global decorators and react-testing-library [no issue]
  @ornikar/jest-config-react/__mocks__/@storybook/react.js
  @ornikar/jest-config-react/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :warning: Breaking Changes, frontend
