Repository ornikar/shared-configs, pull requests merged in 2020-04, with the labels that each got.

#334 feat: add blacklisted properties ONK-4162
  @ornikar/stylelint-config/index.js
Labels: :ok_hand: code/approved, frontend

#340 feat: jest mock portal for testing library ONK-4263
  @ornikar/jest-config-react/test-setup.js
Labels: :ok_hand: code/approved, frontend

#341 feat(jest-config-react): remove enzyme ONK-4323
  @ornikar/jest-config-react/__mocks__/@storybook/react.js
  @ornikar/jest-config-react/jest-preset.js
  @ornikar/jest-config-react/package.json
  @ornikar/jest-config-react/test-setup.js
  yarn.lock
Labels: :ok_hand: code/approved, frontend

#350 revert: fix(deps): update dependency chalk to v4 [no issue]
  @ornikar/jest-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, frontend

#351 revert: fix(deps): update dependency cross-env to v7 [no issue]
  @ornikar/repo-config-react/package.json
  @ornikar/repo-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, frontend

#352 revert: fix(deps): update dependency stylelint-order to v4 [no issue]
  @ornikar/stylelint-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, frontend

#354 feat: update node version to 12 [no issue]
  .circleci/config.yml
  @ornikar/browserslist-config/package.json
  @ornikar/commitlint-config/package.json
  @ornikar/eslint-config-babel-use/package.json
  @ornikar/eslint-config-babel/package.json
  @ornikar/eslint-config-formatjs/package.json
  @ornikar/eslint-config-node/package.json
  @ornikar/eslint-config-react/package.json
  @ornikar/eslint-config-typescript-react/package.json
  @ornikar/eslint-config-typescript/package.json
  @ornikar/eslint-config/package.json
  @ornikar/intl-config/package.json
  @ornikar/jest-config-react/package.json
  @ornikar/jest-config/package.json
  @ornikar/lerna-config/package.json
  @ornikar/postcss-config/package.json
  @ornikar/prettier-config/package.json
  @ornikar/renovate-config/package.json
  @ornikar/repo-config-react/package.json
  @ornikar/repo-config/package.json
  @ornikar/rollup-config/package.json
  @ornikar/stylelint-config/package.json
  @ornikar/webpack-config/package.json
Labels: :ok_hand: code/approved, :warning: Breaking Changes, frontend

#353 feat: require prettier version to new major [no issue]
  @ornikar/eslint-config/package.json
  @ornikar/prettier-config/package.json
  @ornikar/stylelint-config/package.json
Labels: :ok_hand: code/approved, :warning: Breaking Changes, frontend

#355 fix: update dependency chalk to v4 [no issue]
  @ornikar/jest-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, frontend

#357 fix(eslint-config-react): react/sort-comp rule static-variables [no issue]
  @ornikar/eslint-config-react/rules/react.js
Labels: :ok_hand: code/approved, frontend

#359 fix: unmount components after rendering them [no issue]
  @ornikar/jest-config-react/__mocks__/@storybook/react.js
Labels: :ok_hand: code/approved, frontend

#360 feat: remove intl polyfill [no issue]
  @ornikar/jest-config/package.json
  @ornikar/jest-config/test-shim.js
  yarn.lock
Labels: :ok_hand: code/approved, :warning: Breaking Changes, frontend

#361 chore: update node engine to lts [no issue]
  @ornikar/jest-config/test-setup-after-env.js
  @ornikar/renovate-config/package.json
  package.json
Labels: :ok_hand: code/approved, frontend

#297 feat(renovate-config): split shared configs and enable prs [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, frontend

#365 revert: chore(deps): update dependency lint-staged to v10 [no issue]
  @ornikar/repo-config/package.json
  package.json
  yarn.lock
Labels: :ok_hand: code/needs-review, frontend

#366 fix: tsconfig generator [no issue]
  @ornikar/lerna-config/generate-tsconfig-files.js
Labels: :ok_hand: code/needs-review, frontend
