Repository ornikar/shared-configs, pull requests merged in 2021-03, with the labels that each got.

#466 feat(rollup-config): rollup 2 ARCH-901
  .circleci/config.yml
  @ornikar/rollup-config/README.md
  @ornikar/rollup-config/createRollupConfig.js
  @ornikar/rollup-config/package.json
  @ornikar/rollup-config/rollup-plugin-ignore-browser-only-imports.js
  yarn.lock
Labels: :ok_hand: code/approved, frontend

#469 feat: update testing-library/react v11 & testing-library/react-hooks to v5 [no issue]
  @ornikar/jest-config-react/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :warning: Breaking Changes, frontend

#468 fix(lerna-config): eslintrc generator fix prettier config [no issue]
  @ornikar/lerna-config/bin/generate-eslintrc-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#471 feat(renovate-config): add missing eslint-config-formatjs [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge, frontend
