Repository ornikar/shared-configs, pull requests merged in 2021-12, with the labels that each got.

#573 fix(repo-config): run yarn dedupe fewer, like renovate does [no issue]
  @ornikar/repo-config/createLintStagedConfig.js
Labels: :ok_hand: code/approved, :soon: automerge

#574 fix(lerna-config): add missing stories files in tsconfig.build.json [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge

#576 fix(lerna-config): tsconfig allow 'react-native', 'react-jsx', 'preserve' and go back to 'preserve' by default MB2C-102
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#575 fix(storybook-config): alias is a regexp [no issue]
  @ornikar/storybook-config/webpack-configs/lib.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#572 fix(storybook-config): move addon-essentials to peer dep to avoid duplicates [no issue]
  @ornikar/storybook-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#578 fix(lerna-config): allow apps and examples to extends from something else [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#580 fix(lerna-config): match with rollup-config to determine when to build with rollup, using package.private [no issue]
  @ornikar/lerna-config/bin/generate-eslintrc-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#581 feat(storybook-config): add *.stories.{ts,tsx} [no issue]
  @ornikar/storybook-config/index.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#582 fix(jest-config-react-native): use wrapper option in storybook mock [no issue]
  @ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#579 fix(renovate-confg): change eslint configs group as no longer in shared-configs [no issue]
  @ornikar/renovate-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#587 feat(rollup-config): build for node 14 [no issue]
  @ornikar/rollup-config/createRollupConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#585 chore: fix eslint config [no issue]
  @ornikar/intl-config/.eslintrc.json
  @ornikar/renovate-config/.eslintrc.json
  @ornikar/repo-config-react/.eslintrc.json
  @ornikar/repo-config/.eslintrc.json
  package.json
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#586 feat(rollup-config): stop building dev version [no issue]
  @ornikar/rollup-config/createRollupConfig.js
  @ornikar/rollup-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#588 feat(rollup-config): react-native builds [no issue]
  @ornikar/rollup-config/createRollupConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#590 feat(rollup-config): support multiple entries [no issue]
  @ornikar/rollup-config/createRollupConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#591 fix(lerna-config): dont add dep path in rootDirs [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#595 fix: downgrade node minimum required version [no issue]
  @ornikar/browserslist-config/package.json
  @ornikar/commitlint-config/package.json
  @ornikar/intl-config/package.json
  @ornikar/jest-config-react-native-web/package.json
  @ornikar/jest-config-react-native/package.json
  @ornikar/jest-config-react/package.json
  @ornikar/jest-config/package.json
  @ornikar/lerna-config/package.json
  @ornikar/postcss-config/package.json
  @ornikar/prettier-config/package.json
  @ornikar/renovate-config/package.json
  @ornikar/repo-config-react/package.json
  @ornikar/repo-config/package.json
  @ornikar/rollup-config/package.json
  @ornikar/stylelint-config/package.json
  @ornikar/webpack-config/package.json
  package.json
Labels: :ok_hand: code/approved, :soon: automerge

#597 fix(lerna-config): support empty entries in generators [no issue]
  @ornikar/lerna-config/bin/generate-eslintrc-files.js
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#596 fix(rollup-config): replace options [no issue]
  @ornikar/rollup-config/createRollupConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#602 feat(repo-config): prettier env INSTRUCTOR-361
  @ornikar/repo-config/bin/ornikar-prettier-check.sh
  @ornikar/repo-config/bin/ornikar-prettier-fix.sh
  @ornikar/repo-config/createLintStagedConfig.js
  @ornikar/repo-config/package.json
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#603 fix(repo-config): missing dependency [no issue]
  @ornikar/repo-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#598 ci: main [no issue]
  .circleci/config.yml
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#601 feat(jest-config-react): remove random wait, add global addParameters [no issue]
  @ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx
  @ornikar/jest-config-react/__mocks__/@storybook/react.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#605 feat(rollup-config): add platform os support with specific builds [no issue]
  @ornikar/rollup-config/createRollupConfig.js
  @ornikar/rollup-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#606 feat(rollup-config): add babel-plugin-styled-components [no issue]
  @ornikar/rollup-config/createRollupConfig.js
  @ornikar/rollup-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#609 fix(lerna-config): allow library to self import [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#604 fix(lerna-config): sort packages to prevent random changes [no issue]
  @ornikar/lerna-config/index.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#607 fix(rollup-config): fix `!__DEV__` [no issue]
  @ornikar/rollup-config/createRollupConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#610 feat: check translations duplicates project wide and not only section wide [no issue]
  @ornikar/intl-config/generate-translations.js
Labels: :ok_hand: code/approved, frontend
