Repository ornikar/shared-configs, pull requests merged in 2021-11, with the labels that each got.

#533 fix: do not apply postcss addon if cra preset is present [no issue]
  @ornikar/storybook-config/index.js
Labels: :ok_hand: code/approved

#534 feat: drop timezone-mock in favor of env variable [no issue]
  @ornikar/jest-config/global-mocks.js
  @ornikar/jest-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, :warning: Breaking Changes

#536 feat(storybook-config): default layout fullscreen [no issue]
  @ornikar/storybook-config/defaultParameters.js
Labels: :ok_hand: code/approved, :soon: automerge

#538 docs(rollup-config): update readme with links to confluence [no issue]
  @ornikar/rollup-config/README.md
Labels: :ok_hand: code/approved, :soon: automerge

#541 feat(lerna-config): support react 17 [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge

#543 fix(rollup-config): do not build private packages [no issue]
  @ornikar/rollup-config/createRollupConfig.js
Labels: :ok_hand: code/approved, :soon: automerge

#542 feat(lerna-config): support monorepo with apps or examples [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge

#544 fix(lerna-config): dont add paths in tsconfig for private packages [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge

#545 fix(repo-config): allow repo to have no tsconfig.build.json for prettier [no issue]
  @ornikar/repo-config/createLintStagedConfig.js
Labels: :ok_hand: code/approved, :soon: automerge

#550 feat: add waitFor in stories mock [no issue]
  @ornikar/jest-config-react-native/__mocks__/@storybook/react-native.jsx
  @ornikar/jest-config-react/__mocks__/@storybook/react.js
Labels: :ok_hand: code/approved, :soon: automerge

#551 fix(lerna-config): sort packages [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
  @ornikar/lerna-config/index.js
Labels: :ok_hand: code/approved, :soon: automerge

#552 fix(repo-config): fix lint-staged warnings [no issue]
  @ornikar/repo-config/createLintStagedConfig.js
Labels: :ok_hand: code/approved, :soon: automerge

#559 chore: fix security issue npmcli/git [no issue]
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge

#563 fix(webpack-config): remove throw when mainFields already defined as its often the case [no issue]
  @ornikar/webpack-config/resolveFields.js
Labels: :ok_hand: code/approved, :soon: automerge
