Repository ornikar/shared-configs, pull requests merged in 2022-01, with the labels that each got.

#613 feat: let identical translations pass if from similar file and same default messages [no issue]
  @ornikar/intl-config/generate-translations.js
Labels: :ok_hand: code/approved, frontend

#614 feat: generate translations script returns a part of phrase config [no issue]
  @ornikar/intl-config/generate-translations.js
Labels: :ok_hand: code/approved, frontend

#616 feat(jest-config): set timezone to utc in config [no issue]
  @ornikar/jest-config/jest-global-setup.ts
  @ornikar/jest-config/jest-preset.js
Labels: :ok_hand: code/approved

#618 fix: shared configs/fix jest configs CME-51
  @ornikar/jest-config-react-native-web/package.json
  @ornikar/jest-config-react/jest-preset.js
  @ornikar/jest-config-react/package.json
  @ornikar/jest-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved

#617 feat(jest-config-react): add styled-components module name mapper [no issue]
  @ornikar/jest-config-react/jest-preset.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#619 feat(lerna-config): use react-jsx in tsconfig [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#620 feat(jest-config-react): mock @storybook/react-native [no issue]
  @ornikar/jest-config-react/jest-preset.js
Labels: :ok_hand: code/approved, :soon: automerge

#622 feat(lerna-config): get sync packages [no issue]
  @ornikar/lerna-config/index.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#623 feat(repo-config): add native lockfiles [no issue]
  @ornikar/repo-config/lib/postinstall/install-husky.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#570 fix(jest-config): support next-gen jest-circus runner [no issue]
  @ornikar/jest-config/package.json
  @ornikar/jest-config/test-setup-after-env.js
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#630 feat: jest-config native and web improvements [no issue]
  @ornikar/jest-config-react-native-web/jest-preset.js
  @ornikar/jest-config-react-native/jest-preset.js
  @ornikar/jest-config-react-native/nativeSnapshotResolver.js
  @ornikar/jest-config-react-native/package.json
  @ornikar/jest-config-react-native/svg-transformer.js
  @ornikar/jest-config-react/jest-preset.js
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#621 feat(rollup-config): add optional linaria rollup [no issue]
  @ornikar/rollup-config/createRollupConfig.js
  @ornikar/rollup-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#632 feat(rollup-config): build node web variant [no issue]
  @ornikar/rollup-config/createRollupConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#633 feat(storybook-config): support react-native-web [no issue]
  @ornikar/storybook-config/addon/defaultOptions.js
  @ornikar/storybook-config/addon/webpackFinal.js
  @ornikar/storybook-config/index.js
  @ornikar/storybook-config/package.json
  @ornikar/storybook-config/preset.js
  @ornikar/storybook-config/webpack-configs/app.js
  @ornikar/storybook-config/webpack-configs/base.js
  @ornikar/storybook-config/webpack-configs/cssModulesRule.js
  @ornikar/storybook-config/webpack-configs/lib.js
  @ornikar/storybook-config/webpack-configs/reactNativeWeb.js
  @ornikar/storybook-config/webpack-configs/svgRule.js
  @ornikar/webpack-config/inlineSvg.js
  @ornikar/webpack-config/linaria.js
  @ornikar/webpack-config/processEnv.js
  @ornikar/webpack-config/rawSvg.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#638 feat(jest-config-react-native): support svg with svgr named loader CME-229
  @ornikar/jest-config-react-native/jest-preset.js
  @ornikar/jest-config-react-native/svg-transformer-inline.js
  @ornikar/jest-config-react-native/svg-transformer.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend
