Repository ornikar/shared-configs, pull requests merged in 2022-08, with the labels that each got.

#757 feat(lerna-config): adapt generator for legacy project [no issue]
  @ornikar/lerna-config/bin/generate-tsconfig-files.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#762 feat(repo-config): skip husky install on ci [no issue]
  @ornikar/repo-config/lib/postinstall/install-husky.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#756 feat(jest-config-react-native): support for react-native-svg-web ELN-3031
  @ornikar/jest-config-react-native/web/jest-preset.js
Labels: :ok_hand: code/approved, frontend

#764 feat(prettier-config): use overrides to configure dotenv ARCH-1558
  .yarn/cache/fsevents-patch-3340e2eb10-8.zip
  .yarn/cache/fsevents-patch-fcdf30aaca-8.zip
  @ornikar/prettier-config/.npmignore
  @ornikar/prettier-config/index.js
  @ornikar/prettier-config/package.json
  @ornikar/prettier-config/test/.env
  @ornikar/prettier-config/test/test.env
  @ornikar/repo-config/bin/ornikar-prettier-check.sh
  @ornikar/repo-config/bin/ornikar-prettier-fix.sh
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#765 fix(repo-config): fix prettier env files [no issue]
  @ornikar/repo-config/createLintStagedConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#766 feat(commitlint-config): add monorepo config [no issue]
  .yarn/cache/@commitlint-config-lerna-scopes-npm-17.0.2-e9d31f3681-7ec3c40c0c.zip
  .yarn/cache/import-from-npm-4.0.0-e5a38cbb8a-1fa29c05b0.zip
  .yarn/cache/resolve-pkg-npm-2.0.0-7b70eb3262-4a14cc38ef.zip
  @ornikar/commitlint-config/monorepo.js
  @ornikar/commitlint-config/package.json
  package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#763 feat: phrase pre-push hook [no issue]
  @ornikar/repo-config/lib/postinstall/install-husky.js
  @ornikar/repo-config/lib/postinstall/phrase-pre-push.js
Labels: :ok_hand: code/approved, frontend

#769 feat(repo-config): only run tsc on pre-commit when ts file changed [no issue]
  @ornikar/repo-config/createLintStagedConfig.js
  @ornikar/repo-config/lib/postinstall/install-husky.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#770 feat(repo-config): drop yarn-deduplicate [no issue]
  .yarn/cache/@yarnpkg-lockfile-npm-1.1.0-6e0da4acd2-05b881b486.zip
  .yarn/cache/commander-npm-6.2.1-d5b635f237-d7090410c0.zip
  .yarn/cache/yarn-deduplicate-npm-3.1.0-5fd65bedb6-780d4b6df8.zip
  @ornikar/repo-config/createLintStagedConfig.js
  @ornikar/repo-config/package.json
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend, :warning: Breaking Changes

#537 feat: make create lint staged handle big commits better [no issue]
  @ornikar/repo-config/bin/ornikar-lint-staged.mjs
  @ornikar/repo-config/createLintStagedConfig.js
Labels: :ok_hand: code/approved, :soon: automerge, frontend
