Repository ornikar/shared-configs, pull requests merged in 2022-10, with the labels that each got.

#794 fix: previous release was breaking [no issue]
  @ornikar/postcss-config/README.md
Labels: :ok_hand: code/approved, frontend, :warning: Breaking Changes

#797 chore: add codeowners ARCH-1581
  .github/CODEOWNERS
Labels: :ok_hand: code/approved, :soon: automerge, frontend

#798 feat: use generic release alert workflow instead of local one
  .github/workflows/release-alert.yml
Labels: :ok_hand: code/approved, frontend

#799 chore: fix security issue [no issue]
  .yarn/cache/@xmldom-xmldom-npm-0.7.5-f6fb7cf202-8d7ec35c1e.zip
  .yarn/cache/@xmldom-xmldom-npm-0.7.6-f88f0bfdcb-3c31dcd909.zip
  yarn.lock
Labels: :ok_hand: code/approved, :soon: automerge, frontend
